"""
User domain model
This represents a user in the system with authentication capabilities
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, EmailStr, Field


class User(BaseModel):
    """
    User model - represents an authenticated user
    
    Attributes:
        id: Unique identifier (generated by SurrealDB as record ID)
        username: Unique username for login
        email: Unique email address
        password_hash: Hashed password (never store plain text!)
        created_at: When the account was created
        updated_at: Last update timestamp
        is_active: Whether the account is active
        last_login: Last successful login time
    """
    id: Optional[str] = None
    username: str = Field(..., min_length=3, max_length=50)
    email: EmailStr
    password_hash: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    is_active: bool = True
    last_login: Optional[datetime] = None

    class Config:
        json_schema_extra = {
            "example": {
                "username": "john_doe",
                "email": "john@example.com",
                "is_active": True
            }
        }


class UserCreate(BaseModel):
    """Schema for creating a new user (signup)"""
    username: str = Field(..., min_length=3, max_length=50)
    email: EmailStr
    password: str = Field(..., min_length=8)


class UserLogin(BaseModel):
    """Schema for user login"""
    username: str
    password: str


class UserResponse(BaseModel):
    """Public user data (never expose password_hash!)"""
    id: str
    username: str
    email: str
    created_at: datetime
    is_active: bool
    last_login: Optional[datetime] = None


class Token(BaseModel):
    """JWT token response"""
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


class PasswordResetRequest(BaseModel):
    """Schema for requesting password reset"""
    email: EmailStr


class PasswordReset(BaseModel):
    """Schema for resetting password with token"""
    token: str
    new_password: str = Field(..., min_length=8)
